### ISSUE TITLE
Future of the project. HAML vs HAMLIT

### ISSUE THREAD

**Issue by mickey** [k0kubun/hamlit#115]
Hello there,

At my current company, we're on haml 4 and were planning for a while to migrate to hamlit for the better performances.
We're now seeing that you contributed a lot to haml and that haml 5 was finally release with, among other things, way better performance even if it's still not on par with hamlit.

So we were wondering on which horse we should jump, what do you plan for hamlit and haml? Is there some kind of roadmaps for the 2 projects? Does it even matter which one we choose?

Thanks in advance for you reply

**Comment by k0kubun** [comment]
## Differences

| Hamlit       | Haml           |
|:-------------|:-------------|
| 2x faster      | 2x slower, and performance never reaches Hamlit's one |
| No useless features by design     | Much unnecessary legacy features that can't be dropped for backward compatibility  |
| No monkey-patch  | Too many monkey-patches to ActionView, Sprockets  |
| Maintained only by me  | Maintained mainly by me  |
| 4 pending issues, 1 open PR  | 18 pending issues, 3 open PR   |
| New feature will be available immediately | New feature will be shipped slowly |

Which do you prefer? I definitely prefer Hamlit. So it'll continue to be maintained.

## Roadmap
### Hamlit
- Replace parser to Haml 5 based one
  - I may modify Haml too to have more maintainable architecture to share parser
- Will have Java extension support, hopefully it'll be much faster than Haml
- Have idea to improve C extension performance, so it may improve later
- Continue to be maintained by me

### Haml
- May have HTTP Streaming support
- Have idea to improve performance around `Haml::Buffer`, so it may have performance similar to [Faml](https://github.com/eagletmt/faml)
  - But it never reaches the performance of Hamlit, because of its design and for backward compatibility
- Continue to be maintained by me

**Comment by mickey** [comment]
Awesome! Thanks for the fast and complete reply!
And thanks a lot for the sweat and blood you're giving to the whole community!

❤️  ❤️
