### ISSUE TITLE
Sinatra content_for throws an error when using hamlit

### ISSUE THREAD

**Issue by drum445** [k0kubun/hamlit#150]
Hello,
Latest sinatra
Latest hamlit

When using sinatra's yield_content helper I get the following error:
undefined method `with_haml_buffer' for #`

Example code:
`layout.haml`
```haml
!!!
%html
  %head
    %title== MySite | #{yield_content :title}
  %body
    .container
      != yield
```
`home.haml`
```haml
- content_for(:title, "Home")

%h3 Home page content
```

Hopefully it's clear what I'm trying to do.
Please let me know if I shouldn't be using sinatra's yield_content helper and if hamlit has its own.
FYI, it works as expected when using normal haml.

Many Thanks

**Comment by WaKeMaTTa** [comment]
This code `!= yield` it should be `= yield`

**Comment by WaKeMaTTa** [comment]
And `%title== MySite | #{yield_content :title}` should be `%title=
yield_content(:title)
|| "MySite"

**Comment by WaKeMaTTa** [comment]
This code `!= yield` it should be `= yield`.

And `%title== MySite | #{yield_content :title}` should be `%title=
yield_content(:title)
|| "MySite"`

**Comment by k0kubun** [comment]
sinatra-contrib's `yield_content` implementation has not supported Hamlit yet. I implemented that in https://github.com/sinatra/sinatra/pull/1580. Please use [my fork](https://github.com/k0kubun/sinatra/tree/hamlit-support) for the time being.
By the nature of sinatra-contrib implementation, you may also need to use hamlit-block.gem if you're using capturing with a block.

Let me close this issue because I have nothing to do on my side.
