### ISSUE TITLE
Support for Third Party Component Libraries (ViewComponent)

### ISSUE THREAD

**Issue by mc962** [k0kubun/hamlit#156]
Will there be any issues with Hamlit supporting Third Party Component libraries such as github's [view_component](https://github.com/github/view_component) library?

I have been looking at hamlit for a project, while also following recent Rails developments concerning integrating third-party component libraries such as described in the https://github.com/rails/rails/pull/36388 PR.

From reading the description of both the Rails PR and view_component, it seems like they will support haml, and it seems like in general if haml is supported then hamlit will be supported. 
But I want to confirm if there might be issues with integrating hamlit with component libraries, when they are supported/released in Rails.

**Comment by k0kubun** [comment]
Looking at `TestComponent` in https://github.com/rails/rails/pull/36388, that seems totally feasible. 

In that example, I think it should work by just changing `ActionView::Template::Handlers::ERB.erb_implementation.new(template, trim: true).src` to `Hamlit::RailsTemplate.call(template)`. 

Let me close this as I'm still not sure what should be done in hamlit.gem side, but please reopen this if you have ideas of things to be done here.

**Comment by k0kubun** [comment]
It's intentional that Hamlit doesn't offer most of Haml's helpers like `haml_tag`. [REFERENCE.md](https://github.com/k0kubun/hamlit/blob/master/REFERENCE.md#haml-helpers-are-still-in-development) says it's under development, but it's actually a wont-fix at this point. If you're using Rails, you should be able to use `content_tag`. Even if it doesn't work or doesn't even exist, you should be able to define such a helper yourself. Helpers in a rendering context are something template engines shouldn't care about, e.g. Slim and ERB don't, because it requires monkey-patching.

> (didn't get the error with haml)

Note that Haml is going to remove `haml_tag` too. If you use the `main` branch of haml/haml, you cannot use `haml_tag`.
