### ISSUE TITLE
Minor issue with rendering blocks inside templates

### ISSUE THREAD

**Issue by dux** [k0kubun/hamlit#191]
I have this peace of code

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/48320/185563540-992b2b1c-bb67-49a4-ae92-9014187be495.png">

Before, I called blocks like 

```ruby
= @gen.call('Active modules', :selected) {|code| @org.use(code) }
```

and now in v3 this produces some junk output, so right way to call it is as in image

```ruby
- @gen.call('Active modules', :selected) {|code| @org.use(code) }
```

this does not produce junk. How does junk look like? Like this

<img width="346" alt="image" src="https://user-images.githubusercontent.com/48320/185563965-c5ba54c1-f2aa-4224-8d03-6e94eba12c9a.png">

To me, former behaviour is the right one `= @block.call ` and not `- @block.call`, so I am posting this issue. I know it is fringe border one, I really use this rarely.

**Comment by k0kubun** [comment]
Can you create a minimum repository that reproduces this issue? I cannot run your code in your screenshot, e.g. you didn't provide the definition of `Apps`.

**Comment by dux** [comment]
I can, but the issue is simple.

1. proc can be created as expected
2. when you want to call it and add proc response to output, in v3 you have to use `- foo.call` and in v2, I used `= foo.call`

if I use `= foo.call` in v3, I get expected result + junk.

To me it looks like you somewhere return stack array where you before returned nil.

Still need failing test?

**Comment by k0kubun** [comment]
Yes, that'd be really useful. At least I cannot run the code in your screenshot. If you don't want to create a repository, you may write a single Haml template in a comment that could be rendered with `hamlit render template.haml`.

**Comment by k0kubun** [comment]
Thank you for adding the test! That was really helpful for me.

> when you want to call it and add proc response to output, in v3 you have to use - foo.call and in v2, I used = foo.call

Which version was your "v2"? I checked out v2.16.2, added your test, and ran it, but it failed the same way. I think you can reproduce the same thing now that we have the reproduction repository we wanted. I'd like to know which version started to cause the issue.

**Comment by dux** [comment]
> I'd like to know which version started to cause the issue.

Sorry I cant help you with that. I used `hamlit` + `hamlit-block` and it worked fine. This was only issue I had when migrating to V3 on a pretty large project.

When I upgraded to V3, it did not work, but when I removed `hamlit-block` gem, then it worked, that is all I remember. After that, this was the only Issue I encountered.

**Comment by k0kubun** [comment]
> This was only issue I had when migrating to V3 on a pretty large project.

I'm so sorry. hamlit-block was a weird-behaving gem, which is why I implemented it as a separate gem, and I finally figured out a sustainable way to achieve the goal, which is to use the same strategy as Slim as they share the same framework.

So, it's the intended behavior going forward. Sorry about the migration effort, but this behavior is intended in v3.

Do you have any other questions?

**Comment by k0kubun** [comment]
To clarify why the "junk output" is intended, by the very nature of template engine implementation, a template engine needs to decide whether it returns a value or writes to a shared buffer for every code fragment. Because most template engines use a variable visible to a block for a shared buffer, it needs to give up supporting either returning a value or writing to a shared buffer when compiling a block. So, if you use a block in a template, it may or may not work. It's impossible to always prevent a "junk output" in a block. For that reason, you'd like a way to switch the behavior, and it's in fact switched by whether it's `-` or `=` here.

**Comment by dux** [comment]
ok, thx.

I just thought that `-` suppresses all output and just calculates data as `<% ... %>`, so this looked logical to report.

If that makes a lot pf problems for you because of gem internals, all ok, not a problem at all.

**Comment by k0kubun** [comment]
It's just that only either

```rb
- users.each do |user|
  %p= user.name
```

or 

```rb
- @gen = proc do |user|
  %p= user.name
```

could be supported because the second line of each template needs to do completely different things while they look like the same thing to Haml. And I believe the former is a more common use case, which is why I can't support the latter.

**Comment by dux** [comment]
I get it now, and ofc agree. Thank you.
