### ISSUE TITLE
Fix Ruby 1.9 compatibility

### ISSUE THREAD

**Issue by tardate** [k0kubun/hamlit#21]
I discovered by trial that there seems to be an implicit ruby 2+ requirement for hamlit (first issue I hit was the use of ruby 2 keyword arguments).

I don't think that's necessarily a bad thing, but if this is intentional it might be good to declare the requirement in the readme and perhaps [`required_ruby_version`](http://guides.rubygems.org/specification-reference/#required_ruby_version=) in the gemspec.

If this is intentional, I'd be happy to do a P/R for it. Or if 1.9 compatibility is desired, delve into how big a deal this would be. But which is it?

**Comment by k0kubun** [comment]
Thank you for submitting an issue.
This is not intentional. I didn't care about it seriously.
While 1.9 compatibility is not a big deal for me, I want to increase coverage of supported versions because it is not so difficult in this case.

**Comment by tardate** [comment]
Ahah. No problem! I'll rename this issue accordingly to clarify the situation.

If I get a chance, I'll see if I can offer any P/Rs to help.

**Comment by k0kubun** [comment]
Because one of development dependency does not support Ruby 1.9, I gave up to support Ruby 1.9. 
See https://github.com/eagletmt/faml/issues/20.
In addition, I don't recommend to use Ruby which is no longer supported.

Thus I dropped support of Ruby 1.9 and added required_ruby_version 6ca14b072a729dc08bb2faa4b44a223db125c276. 
Sorry for changing my opinion.
