### ISSUE TITLE
Hamlit and cache blocks

### ISSUE THREAD

**Issue by marionzualo** [k0kubun/hamlit#56]
Hi,

I am trying to switch from haml to hamlit and I am having some issues with the following type of code:
```haml
  - cache "test" do
    %h2 Test
```
While the code above was working with haml it is not being rendered with hamlit. I did not find anything in the docs regarding how this should be handled.

Should I change  the code? How? I noticed that `hamlit-block` exists but I could not understand how it is supposed to affect the code above.

Thanks for the work with `hamlit`. Looks promising!

**Comment by k0kubun** [comment]
Thank you for trying Hamlit and reporting the issue!

I guess it is rails application since Haml and Hamlit don't have `cache` helper. I couldn't reproduce your issue in my local rails app and test cases I wrote for this. Doesn't the part render `<h2>Test</h2>`? I wrote such a template, tried running rails app in both development and production environments and it worked.

Could you try removing your fragment cache? If it doesn't work, please tell me the detail to reproduce your problem. Any sample repository would be appreciated.

**Comment by marionzualo** [comment]
Thanks for the quick reply. 
I will dig a bit more to try to understand what is happening. It just seemed strange for the bare change of the template engine to make those blocks to stop working. So I assumed that perhaps I did something wrong when changing the gems and that perhaps it could have been a frequent misstep.
I will investigate this further in the coming days and come back to you. Thanks.

**Comment by marionzualo** [comment]
I found the issue. I had put `hamlit-block` in my Gemfile (as suggested [here](https://github.com/trailblazer/cells-hamlit)) because I wanted to use `cells-hamlit` and whenever I add hamlit-block to the Gemfile the cache block stops working.

I will cose the issue for now since I found the cause of the problem. Thanks!

**Comment by k0kubun** [comment]
Sorry for confusing you. hamlit-block is a gem to allow non-rails applications to work cells-hamlit and breaks some compatibility for it. If you're using rails, I personally recommend you to use cells-hamlit v0.1.0 and no hamlit-block until https://github.com/trailblazer/cells-hamlit/pull/2 is merged. See https://github.com/hamlit/hamlit-block/issues/1 for detail.

**Comment by marionzualo** [comment]
@k0kubun I ended up your fork of cells-hamlit as done in trailblazer/cells-hamlit#2. for now. Thanks for the help.

**Comment by k0kubun** [comment]
I'm glad to hear it works for you!
