### ISSUE TITLE
please declare ruby version dependency

### ISSUE THREAD

**Issue by grosser** [k0kubun/hamlit#67]
always installing latest and then failing ... would be nice to see a real error and be able to check which version requires which ruby version on rubygems

**Comment by k0kubun** [comment]
Thank you for reporting an issue. I should have done that in https://github.com/k0kubun/hamlit/issues/21.
Added ruby version dependency on rubygems. https://rubygems.org/gems/hamlit/versions/2.3.1

Since I don't know how to change old versions' dependency, I tell you that 2.2.2+ require Ruby 2.1 and others require Ruby 2.0.0.
