### ISSUE TITLE
ruby 2.3 frozen string literals?

### ISSUE THREAD

**Issue by kikonen** [k0kubun/hamlit#81]
Haven't investigated logic of hamlit deeply, but just noticing that hamlit is using ".freeze" for its' own string literals in compiled template. I ponder what would happen if there would be option support to including ruby 2.3.1 pragma to apply that to all string literals in template.

```
# frozen-string-literal: true
```

**Comment by k0kubun** [comment]
If the suggestion is all about compiled template, I suppose nothing would happen since `.freeze` is automatically added to static strings and most of others should not have `.freeze`. Did you find any template whose compiled template has string literal that can be optimized by `# frozen-string-literal: true`? I'll fix the case.

And there's another reason I'm reluctant to do that. We should keep the line number of compiling template in compiled template for convenient error message. The `# frozen-string-literal: true` line breaks it and we have to change the argument of `eval` that reads a compiled template as the template starts from not 1 but 0. I don't want to change internal of Rails or Tilt if I can avoid it.

If you're talking about internal of Hamlit, it'd have positive effect to compiling time. In my opinion, Hamlit has been already optimized about frozen string literal.

**Comment by kikonen** [comment]
I was pondering about optimization for strings in template itself. 

For example,
some_large_template.haml
```
= form_for(... id: 'some_id') do |f|
  = render partial: 'some_partial'
...
```
in that case 'some_id' and 'some_partial' would be targets.

**Comment by k0kubun** [comment]
Ahhh... had never thought of that. It's interesting. 

Basically adding `# frozen-string-literal: true` optionally is not difficult and I think it's possible in any templates. But only my concern is the line number.

**Comment by k0kubun** [comment]
Implemented. https://github.com/hamlit/hamlit-frozen
Just add it to the Gemfile to for the test.

```rb
Hamlit::Engine.new.call("= 'hello world'")
=> "# frozen-string-literal: true\n_buf = []; _buf << (\"hello world\\n\".freeze); \n; _buf = _buf.join(\"\".freeze)"
```

**Comment by kikonen** [comment]
Great I will be trying that out

**Comment by kikonen** [comment]
Tried out; it seemed that PrependFrozen is invoked, but it looks like it wasn't effective (strings didn't get frozen). Perhaps this raills "frozen" pragma works only in explicit ".rb" files only.

**Comment by k0kubun** [comment]
Ah, for rails, the compiled template will become a part of method.
https://github.com/rails/rails/blob/v5.0.0/actionview/lib/action_view/template.rb#L289

So `# frozen-string-literal: true` is out of scope for template engine in ActionView.

**Comment by kikonen** [comment]
Thus dounds, like this is not doable. That leaves possibility for doing some gsub replacing, but may not be worth of effort. Likely should close this.

**Comment by k0kubun** [comment]
Thanks for proposing this 👍
