### ISSUE TITLE
What should I expect when moving from HAML to HAMLIT - not a performance decrease I guess?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [k0kubun/hamlit#95]
I recently discovered this gem. The promising hope of a performance boost to haml template rendering, is really something we could use in our project.

Now as a test, I just tried to remove everything `haml` from my rails 4.2 project, and add the `hamlit`gem instead, that looked something like:

![skaermbillede 2016-12-19 kl 14 05 33](https://cloud.githubusercontent.com/assets/570755/21313814/46d27e8e-c5f4-11e6-8f03-94c3fbab1725.png)

After that, I checked that no references to `haml` was left in my Gemfile.lock neither from me or any gems. I wanted to see what effect this would have on my production env, so I just tried deploying it straight, however the results were not as expected. This is a screenshot of my overall application APM in newrelic before and after the deployment. As you can see, actually rendering speed seems to have gotten down!

![skaermbillede 2016-12-19 kl 13 53 16](https://cloud.githubusercontent.com/assets/570755/21313835/58a1df2e-c5f4-11e6-890d-6d75786a0393.png)

Here is also a screenshot of a more concrete transaction, where you can see, that it's the rendering og haml partials that has actually gone up:

![skaermbillede 2016-12-19 kl 13 54 02](https://cloud.githubusercontent.com/assets/570755/21313714/ad8c5c86-c5f3-11e6-881b-f78d359d75c7.png)

This is not exactly what I would have expected, so I rolled it back of cause. The question is - what should I have expected then? :-)

Ruby 2.3
Rails 4.2
Haml 4.0.7
Hamlit 2.7.5

**Comment by k0kubun** [comment]
That graph tells that instructions in Ruby slows down but doesn't tell that rendering time of a template compiled by Hamlit. There may be some possibilities to cause the situation but I can say nothing fron that graph. 

You should break down what's the difference between them. I recommend you to profile the same action before and after the deployment. For example, NewRelic has Thread Profiler, and I also recommend https://github.com/tmm1/stackprof.

<hr>

For the case you have no time to do that, I explain a little about template engine's performance. ActionView has two phases to render a view. Compiling time and rendering time. Haml is faster than Hamlit in compiling, and Hamlit is faster than Haml in rendering. Since compiling is executed only once per a template after deployment, usually Hamlit is more scalable. But if times to compile a template is not so often or somehow compiled code is not cached by some third-party rubygems, Haml can be faster.

**Comment by WaKeMaTTa** [comment]
Thanks for this explanation:

> For the case you have no time to do that, I explain a little about template engine's performance. ActionView has two phases to render a view. Compiling time and rendering time. Haml is faster than Hamlit in compiling, and Hamlit is faster than Haml in rendering. Since compiling is executed only once per a template after deployment, usually Hamlit is more scalable. But if times to render a template is not so often or somehow compiled code is not cached by ActionView, Haml can be faster.

**Comment by NielsKSchjoedt** [comment]
Hmm that's interesting. How do I know if the comiling part is running more times?

**Comment by k0kubun** [comment]
Compiling may run once or every time. You should profile which method consumes cpu time for a certain action after you request the same action once. If it includes ActionView's method to compile template, there's possibility to compile the template every time. In that case, I would try debugging in development environment.
